# Generated by Django 5.2.13 on 2026-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0006_staff_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_leave',
            name='duration_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
