# Generated by Django 5.2.13 on 2026-05-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0009_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_leave',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
